### ISSUE TITLE
AttributeError: 'DeletedQuerySet' object has no attribute 'hard_delete' when trying to hard-delete in Django Admin

### ISSUE THREAD

**Issue by ksylvan** [san4ezy/django_softdelete#47]
When trying to hard-delete any soft-deleted object from Django Admin that has connected sub-objects, I'm getting the error:

```text
127.0.0.1 - - [02/Nov/2024 04:43:10] "POST /admin/abacus/periodsoftdeleted/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/kayvan/src/condor/.env/lib/python3.13/site-packages/django/contrib/staticfiles/handlers.py", line 80, in __call__
    return self.application(environ, start_response)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kayvan/src/condor/.env/lib/python3.13/site-packages/django/core/handlers/wsgi.py", line 124, in __call__
    response = self.get_response(request)
  File "/Users/kayvan/src/condor/.env/lib/python3.13/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "/Users/kayvan/src/condor/.env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/Users/kayvan/src/condor/.env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
    
  File "/Users/kayvan/src/condor/.env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/Users/kayvan/src/condor/.env/lib/python3.13/site-packages/django_extensions/management/technical_response.py", line 40, in null_technical_500_response
    raise exc_value.with_traceback(tb)
  File "/Users/kayvan/src/condor/.env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/kayvan/src/condor/.env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py", line 85, in inner
    return func(*args, **kwds)
  File "/Users/kayvan/src/condor/.env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/kayvan/src/condor/.env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/Users/kayvan/src/condor/.env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/kayvan/src/condor/.env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/kayvan/src/condor/.env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "/Users/kayvan/src/condor/.env/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/kayvan/src/condor/.env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/Users/kayvan/src/condor/.env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/kayvan/src/condor/.env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2034, in changelist_view
    response = self.response_action(
    
  File "/Users/kayvan/src/condor/.env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 1666, in response_action
    response = func(self, request, queryset)
  File "/Users/kayvan/src/condor/.env/lib/python3.13/site-packages/django_softdelete/admin.py", line 7, in hard_delete_selected_items
    queryset.hard_delete()
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DeletedQuerySet' object has no attribute 'hard_delete'
```

**Comment by Armaqanal** [comment]
make sure to check the model relationships especially the on delete  for foreign keys. If you have related objects  ensure that the on_delete argument is set appropriately, for instance If it is set to PROTECT, Django will prevent the deletion of the object as it has dependent sub-objects.

**Comment by ksylvan** [comment]
There are no `PROTECT` relationships in my code base. The attached PR fixes the issue.

https://github.com/san4ezy/django_softdelete/pull/48

**Comment by ksylvan** [comment]
Fixed by merge of #54
